version: '3'
services:
  db:
    image: postgres:9.6
    container_name: postgres
    ports:
      - 5432:5432
    environment: 
      - PGDATA=/pg 
      - POSTGRES_PASSWORD=postgres 
      - POSTGRES_USER=postgres 
      - POSTGRES_DB=daigou 
    tty: true
  daigou:
    build:
      context: .
      dockerfile: daigou.Dockerfile
    container_name: daigou
    ports:
      - 8088:8088
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    tty: true